name: Terraform Module CI

on:
  pull_request:
    branches: [main]

jobs:
  terraform-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Preview next release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format check
        run: terraform fmt -check -recursive

      - name: Init
        run: terraform init -backend=false

      - name: Validate module
        run: terraform validate